//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmaCoHealth.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Administrator
    {
        [Key]
        public int AdminId { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "First Name")]
        [MinLength(3, ErrorMessage = "Minimum 3 letters are required")]
        [MaxLength(10, ErrorMessage = "Maximum 10 letters are allowed")]
        public string AdminFirstName { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Last Name")]
        [MinLength(3, ErrorMessage = "Minimum 3 letters are required")]
        [MaxLength(10, ErrorMessage = "Maximum 10 letters are allowed")]
        public string AdminLastName { get; set; }

        [Required]
        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Phone Number")]
        [MinLength(11, ErrorMessage = "Minimum 11 Digits")]
        [MaxLength(11, ErrorMessage = "Maximum 11 Digits")]
        public string AdminPhoneNo { get; set; }

        [Required]
        [DataType(DataType.EmailAddress)]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Confirm Password")]
        [Compare("Password", ErrorMessage = "Password and Confirm Password doesn't match")]
        public string ConfirmPassword { get; set; }
    }
}
